export const phpTechnologies = [
  { image: "/images/Laravel.png", name: "Laravel" },
  { image: "/images/PHP-Unit.png", name: "PHP-Unit" },
  { image: "/images/PHP.png", name: "PHP" },
  { image: "/images/MODX.png", name: "MODX" },
  { image: "/images/Cross-PHP.png", name: "Cross-PHP" },
  { image: "/images/Symfony.png", name: "Symfony" },
  { image: "/images/Phaicon.png", name: "Phaicon" },
  { image: "/images/Dash.png", name: "Dash" },
  { image: "/images/UserFrosting.png", name: "UserFrosting" },
  { image: "/images/Mockery.png", name: "Mockery" },
  { image: "/images/CodeIgniter.png", name: "CodeIgniter" },
  { image: "/images/Cake-PHP.png", name: "Cake-PHP" },
  { image: "/images/Zest-Framework.png", name: "Zest-Framework" },
  { image: "/images/Red-Cat.png", name: "Red-Cat" },
  { image: "/images/PHP-Spec.png", name: "PHP-Spec" },
  { image: "/images/Yiifamework.png", name: "Yiifamework" },
  { image: "/images/Ice-Framework.png", name: "Ice-Framework" },
  { image: "/images/Roduck.png", name: "Roduck" },
  { image: "/images/Elefant-cms.png", name: "Elefant-cms" },
];
