// data.tsx

export const clients = [
  {
    id: 1,
    name: "Ajman Land Department",
    country: "UAE",
    image: "/images/ajman-land.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 2,
    name: "Ajman Municipality",
    country: "UAE",
    image: "/images/ajman-municipality.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 3,
    name: "Datalyticx",
    country: "UAE",
    image: "/images/datalyticx.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 4,
    name: "Payorio",
    country: "MEXICO",
    image: "/images/payorio.jpg",
    flag: "/images/mex.png",
  },
  {
    id: 5,
    name: "Trulens",
    country: "UAE",
    image: "/images/trulens.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 6,
    name: "Trudocs",
    country: "UAE",
    image: "/images/trudocs.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 7,
    name: "Chattogram City Corporation",
    country: "BD",
    image: "/images/chattogram-city.jpg",
    flag: "/images/ban.png",
  },
  {
    id: 8,
    name: "Excellence Driving School",
    country: "UAE",
    image: "/images/excellence-driving.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 9,
    name: "Government of Dubai",
    country: "UAE",
    image: "/images/dubai-government.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 10,
    name: "Taskeen",
    country: "UAE",
    image: "/images/taskeen.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 11,
    name: "Al Tyre Motors",
    country: "UAE",
    image: "/images/al-tyre-motors.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 12,
    name: "Rabson Care",
    country: "BD",
    image: "/images/rabson-care.jpg",
    flag: "/images/ban.png",
  },
  {
    id: 13,
    name: "Bartawi",
    country: "UAE",
    image: "/images/bartawi.jpg",
    flag: "/images/uae.png",
  },
  {
    id: 14,
    name: "Etisalat",
    country: "UAE",
    image: "/images/etisalat.jpg",
    flag: "/images/uae.png",
  },
];
