import { FaAppStoreIos, FaWordpressSimple } from "react-icons/fa";
import { IoLogoAndroid } from "react-icons/io5";
import { MdOutlineScreenshotMonitor } from "react-icons/md";
import {
  TbAugmentedReality2,
  TbBulb,
  TbCloudComputing,
  TbServer,
  TbBrain,
} from "react-icons/tb";

export const techEN = [
  {
    id: 2,
    title: "Frontend Development",
    des: "Bring your digital vision to life with expert frontend development at Jionex. We specialize in crafting responsive, high-performance interfaces using modern frameworks like React.js, Angular.js, and Vue.js. Our team ensures seamless user experiences with pixel-perfect design and optimized performance across all devices.",
    icon: <MdOutlineScreenshotMonitor />,
    link: "/tech/frontend-development",
  },
  {
    id: 3,
    title: "Backend Development",
    des: "Power your applications with reliable, scalable, and secure backend systems. At Jionex, we specialize in backend technologies like Node.js, PHP, Python, and .NET to ensure seamless database integration, API development, and business logic execution.",
    icon: <TbServer />,
    link: "/tech/backend-development",
  },

  {
    id: 5,
    title: "Android App Development",
    des: "Build powerful Android apps with Jionex. Our team creates fast, secure, and scalable mobile applications tailored to your goals—ensuring seamless user experiences across all Android devices.",
    icon: <IoLogoAndroid />,
    link: "/tech/android-app",
  },
  {
    id: 6,
    title: "iOS App Development",
    des: "Elevate your brand with premium iOS applications. Jionex crafts high-performance apps for iPhone, iPad, and Apple Watch, combining sleek design with seamless functionality.",
    icon: <FaAppStoreIos />,
    link: "/tech/ios-app",
  },
  {
    id: 7,
    title: "CMS & WordPress Development",
    des: "Jionex offers dynamic CMS solutions, with WordPress at the core. Whether it's a business site, blog, or eCommerce platform, we deliver responsive, secure, and SEO-friendly websites tailored to your brand.",
    icon: <FaWordpressSimple />,
    link: "/tech/wordpress-development",
  },
  {
    id: 8,
    title: "Cloud Computing",
    des: "Empower your business with Jionex’s cloud services. We help you migrate, manage, and scale your infrastructure using AWS, Azure, and Google Cloud—ensuring high availability and efficiency.",
    icon: <TbCloudComputing />,
    link: "/tech/cloud-computing",
  },
  {
    id: 9,
    title: "IoT App Development",
    des: "Connect the physical and digital worlds with Jionex’s IoT solutions. We develop smart IoT applications that gather, analyze, and act on real-time data—improving automation and decision-making across industries.",
    icon: <TbBulb />,
    link: "/tech/iot-app",
  },
  {
    id: 10,
    title: "Augmented Reality Solutions",
    des: "Step into the future with immersive Augmented Reality experiences. Jionex builds interactive AR solutions for retail, real estate, education, and entertainment—bridging the digital and physical worlds.",
    icon: <TbAugmentedReality2 />,
    link: "/tech/augmented-reality",
  },
  {
    id: 11,
    title: "Artificial Intelligence (AI)",
    des: "Transform your business with smart, AI-powered solutions from Jionex. We develop intelligent systems using machine learning, natural language processing, and computer vision to automate workflows, analyze data, and deliver predictive insights.",
    icon: <TbBrain />,
    link: "/tech/artificial-intelligence",
  },
];
export const techES = [
  {
    id: 2,
    title: "Desarrollo Frontend",
    des: "Da vida a tu visión digital con el desarrollo frontend experto de Jionex. Nos especializamos en crear interfaces receptivas y de alto rendimiento utilizando frameworks modernos como React.js, Angular.js y Vue.js. Nuestro equipo garantiza experiencias de usuario fluidas con diseños precisos y rendimiento optimizado en todos los dispositivos.",
    icon: <MdOutlineScreenshotMonitor />,
    link: "/tech/frontend-development",
  },
  {
    id: 3,
    title: "Desarrollo Backend",
    des: "Impulsa tus aplicaciones con sistemas backend confiables, escalables y seguros. En Jionex, nos especializamos en tecnologías backend como Node.js, PHP, Python y .NET para asegurar la integración fluida de bases de datos, desarrollo de APIs y ejecución de lógica empresarial.",
    icon: <TbServer />,
    link: "/tech/backend-development",
  },
  {
    id: 5,
    title: "Desarrollo de Aplicaciones Android",
    des: "Crea potentes aplicaciones Android con Jionex. Nuestro equipo desarrolla aplicaciones móviles rápidas, seguras y escalables adaptadas a tus objetivos, garantizando experiencias de usuario fluidas en todos los dispositivos Android.",
    icon: <IoLogoAndroid />,
    link: "/tech/android-app",
  },
  {
    id: 6,
    title: "Desarrollo de Aplicaciones iOS",
    des: "Eleva tu marca con aplicaciones iOS de alta calidad. Jionex crea aplicaciones de alto rendimiento para iPhone, iPad y Apple Watch, combinando un diseño elegante con funcionalidad impecable.",
    icon: <FaAppStoreIos />,
    link: "/tech/ios-app",
  },
  {
    id: 7,
    title: "Desarrollo de CMS y WordPress",
    des: "Jionex ofrece soluciones CMS dinámicas con WordPress como base. Ya sea un sitio empresarial, blog o plataforma de comercio electrónico, entregamos sitios web receptivos, seguros y optimizados para SEO adaptados a tu marca.",
    icon: <FaWordpressSimple />,
    link: "/tech/wordpress-development",
  },
  {
    id: 8,
    title: "Computación en la Nube",
    des: "Impulsa tu negocio con los servicios en la nube de Jionex. Te ayudamos a migrar, gestionar y escalar tu infraestructura utilizando AWS, Azure y Google Cloud, asegurando alta disponibilidad y eficiencia.",
    icon: <TbCloudComputing />,
    link: "/tech/cloud-computing",
  },
  {
    id: 9,
    title: "Desarrollo de Aplicaciones IoT",
    des: "Conecta los mundos físico y digital con las soluciones IoT de Jionex. Desarrollamos aplicaciones IoT inteligentes que recopilan, analizan y actúan sobre datos en tiempo real, mejorando la automatización y la toma de decisiones en diversas industrias.",
    icon: <TbBulb />,
    link: "/tech/iot-app",
  },
  {
    id: 10,
    title: "Soluciones de Realidad Aumentada",
    des: "Adéntrate en el futuro con experiencias inmersivas de Realidad Aumentada. Jionex crea soluciones AR interactivas para retail, bienes raíces, educación y entretenimiento, uniendo los mundos digital y físico.",
    icon: <TbAugmentedReality2 />,
    link: "/tech/augmented-reality",
  },
  {
    id: 11,
    title: "Inteligencia Artificial (IA)",
    des: "Transforma tu negocio con soluciones inteligentes impulsadas por IA de Jionex. Desarrollamos sistemas inteligentes usando aprendizaje automático, procesamiento de lenguaje natural y visión por computadora para automatizar flujos de trabajo, analizar datos y ofrecer información predictiva.",
    icon: <TbBrain />,
    link: "/tech/artificial-intelligence",
  },
];

export const techBN = [
  {
    id: 2,
    title: "ফ্রন্টএন্ড ডেভেলপমেন্ট",
    des: "আপনার ডিজিটাল ভিশনকে বাস্তবে রূপ দিন Jionex এর ফ্রন্টএন্ড ডেভেলপমেন্টের মাধ্যমে। আমরা React.js, Angular.js, এবং Vue.js এর মতো আধুনিক ফ্রেমওয়ার্ক ব্যবহার করে রেসপনসিভ ও হাই-পারফরম্যান্স ইন্টারফেস তৈরি করি।",
    icon: <MdOutlineScreenshotMonitor />,
    link: "/tech/frontend-development",
  },
  {
    id: 3,
    title: "ব্যাকএন্ড ডেভেলপমেন্ট",
    des: "আপনার অ্যাপ্লিকেশনকে শক্তিশালী করুন নির্ভরযোগ্য, স্কেলেবল এবং সিকিউর ব্যাকএন্ড সিস্টেম দিয়ে। Jionex এ আমরা Node.js, PHP, Python এবং .NET সহ বিভিন্ন টেকনোলজি ব্যবহার করে ডাটাবেজ ইন্টিগ্রেশন, API ডেভেলপমেন্ট এবং বিজনেস লজিক তৈরি করি।",
    icon: <TbServer />,
    link: "/tech/backend-development",
  },

  {
    id: 5,
    title: "অ্যান্ড্রয়েড অ্যাপ ডেভেলপমেন্ট",
    des: "Jionex এর সাথে তৈরি করুন শক্তিশালী, সিকিউর ও স্কেলেবল অ্যান্ড্রয়েড অ্যাপ্লিকেশন। আমাদের টিম আপনার লক্ষ্য অনুযায়ী পারফরম্যান্স-সমৃদ্ধ মোবাইল অ্যাপ ডেভেলপ করে।",
    icon: <IoLogoAndroid />,
    link: "/tech/android-app",
  },
  {
    id: 6,
    title: "iOS অ্যাপ ডেভেলপমেন্ট",
    des: "আপনার ব্র্যান্ডকে উন্নত করুন প্রিমিয়াম iOS অ্যাপ দিয়ে। Jionex তৈরি করে হাই-পারফরম্যান্স iPhone, iPad ও Apple Watch অ্যাপ যা দারুণ ডিজাইন ও স্মুথ ফাংশনালিটি নিশ্চিত করে।",
    icon: <FaAppStoreIos />,
    link: "/tech/ios-app",
  },
  {
    id: 7,
    title: "CMS ও ওয়ার্ডপ্রেস ডেভেলপমেন্ট",
    des: "Jionex ডেলিভার করে ডাইনামিক CMS সল্যুশন, যার কেন্দ্রবিন্দুতে থাকে ওয়ার্ডপ্রেস। বিজনেস সাইট, ব্লগ কিংবা ই-কমার্স—সবকিছুর জন্য তৈরি করি রেসপনসিভ, সিকিউর ও SEO-ফ্রেন্ডলি ওয়েবসাইট।",
    icon: <FaWordpressSimple />,
    link: "/tech/wordpress-development",
  },
  {
    id: 8,
    title: "ক্লাউড কম্পিউটিং",
    des: "Jionex এর ক্লাউড সার্ভিস দিয়ে আপনার ব্যবসাকে দিন নতুন মাত্রা। আমরা AWS, Azure ও Google Cloud ব্যবহার করে ইনফ্রাস্ট্রাকচার মাইগ্রেশন, ম্যানেজমেন্ট এবং স্কেলিং করি—যাতে সর্বোচ্চ এফিশিয়েন্সি নিশ্চিত হয়।",
    icon: <TbCloudComputing />,
    link: "/tech/cloud-computing",
  },
  {
    id: 9,
    title: "IoT অ্যাপ ডেভেলপমেন্ট",
    des: "Jionex এর স্মার্ট IoT সল্যুশনের মাধ্যমে ফিজিক্যাল ও ডিজিটাল দুনিয়াকে একত্রিত করুন। আমরা তৈরি করি এমন অ্যাপ যা রিয়েল-টাইম ডেটা সংগ্রহ করে বিশ্লেষণ ও অটোমেশন সহজ করে।",
    icon: <TbBulb />,
    link: "/tech/iot-app",
  },
  {
    id: 10,
    title: "অগমেন্টেড রিয়েলিটি সল্যুশন",
    des: "ভবিষ্যতের পথে পা রাখুন ইন্টারঅ্যাকটিভ অগমেন্টেড রিয়েলিটির মাধ্যমে। Jionex তৈরি করে রিটেইল, রিয়েল এস্টেট, এডুকেশন ও এন্টারটেইনমেন্ট এর জন্য ইমারসিভ AR সল্যুশন।",
    icon: <TbAugmentedReality2 />,
    link: "/tech/augmented-reality",
  },
  {
    id: 11,
    title: "আর্টিফিশিয়াল ইন্টেলিজেন্স (AI)",
    des: "Jionex এর স্মার্ট AI সল্যুশন দিয়ে ব্যবসাকে দিন নতুন রূপ। আমরা মেশিন লার্নিং, ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিং ও কম্পিউটার ভিশনের মাধ্যমে ইন্টেলিজেন্ট সিস্টেম তৈরি করি।",
    icon: <TbBrain />,
    link: "/tech/artificial-intelligence",
  },
];
export const techAR = [
  {
    id: 2,
    title: "تطوير الواجهة الأمامية",
    des: "حوّل رؤيتك الرقمية إلى واقع مع خدمات تطوير الواجهة الأمامية في Jionex. نحن نبرع في إنشاء واجهات عالية الأداء باستخدام React.js وAngular.js وVue.js، لضمان تجربة مستخدم سلسة وتصميم دقيق الأداء على جميع الأجهزة.",
    icon: <MdOutlineScreenshotMonitor />,
    link: "/tech/frontend-development",
  },
  {
    id: 3,
    title: "تطوير الواجهة الخلفية",
    des: "عزّز تطبيقاتك بأنظمة خلفية موثوقة وقابلة للتوسّع وآمنة. نستخدم في Jionex تقنيات مثل Node.js وPHP وPython و.NET لتكامل سلس مع قواعد البيانات، وتطوير واجهات برمجة التطبيقات، وتنفيذ منطق الأعمال.",
    icon: <TbServer />,
    link: "/tech/backend-development",
  },
  {
    id: 5,
    title: "تطوير تطبيقات أندرويد",
    des: "أنشئ تطبيقات أندرويد قوية مع Jionex. نصمم تطبيقات سريعة وآمنة وقابلة للتوسّع تناسب أهدافك، مع توفير تجربة مستخدم سلسة على جميع أجهزة أندرويد.",
    icon: <IoLogoAndroid />,
    link: "/tech/android-app",
  },
  {
    id: 6,
    title: "تطوير تطبيقات iOS",
    des: "ارتقِ بعلامتك التجارية من خلال تطبيقات iOS عالية الجودة. نقدم تطبيقات احترافية لأجهزة iPhone وiPad وApple Watch بتصميم أنيق وأداء سلس.",
    icon: <FaAppStoreIos />,
    link: "/tech/ios-app",
  },
  {
    id: 7,
    title: "تطوير CMS وWordPress",
    des: "نوفر في Jionex حلول CMS ديناميكية تعتمد على WordPress، سواء لموقع أعمال أو مدونة أو منصة تجارة إلكترونية، ونضمن أن تكون مواقعك متجاوبة وآمنة ومتوافقة مع محركات البحث.",
    icon: <FaWordpressSimple />,
    link: "/tech/wordpress-development",
  },
  {
    id: 8,
    title: "الحوسبة السحابية",
    des: "عزّز أعمالك من خلال خدمات Jionex السحابية. نساعدك على الترحيل والإدارة والتوسّع باستخدام AWS وAzure وGoogle Cloud، لضمان الكفاءة وتوفر الخدمة العالي.",
    icon: <TbCloudComputing />,
    link: "/tech/cloud-computing",
  },
  {
    id: 9,
    title: "تطوير تطبيقات إنترنت الأشياء (IoT)",
    des: "اربط العالم الرقمي بالمادي عبر حلول إنترنت الأشياء من Jionex. نطوّر تطبيقات ذكية تجمع البيانات وتحللها وتتصرف وفقها لتحسين الأتمتة واتخاذ القرار.",
    icon: <TbBulb />,
    link: "/tech/iot-app",
  },
  {
    id: 10,
    title: "حلول الواقع المعزز",
    des: "انطلق نحو المستقبل من خلال تجارب الواقع المعزز التفاعلية. نطوّر في Jionex حلول AR مبتكرة لقطاعات البيع بالتجزئة والعقارات والتعليم والترفيه.",
    icon: <TbAugmentedReality2 />,
    link: "/tech/augmented-reality",
  },
  {
    id: 11,
    title: "الذكاء الاصطناعي (AI)",
    des: "حوّل أعمالك باستخدام حلول Jionex الذكية المدعومة بالذكاء الاصطناعي. نطور أنظمة ذكية باستخدام التعلم الآلي ومعالجة اللغة الطبيعية ورؤية الحاسوب لأتمتة العمليات وتحليل البيانات وتقديم رؤى تنبؤية.",
    icon: <TbBrain />,
    link: "/tech/artificial-intelligence",
  },
];
